apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ${VM_NAME}-sno-cluster
rendezvousIP: ${HOST_IP}
hosts:
  - hostname: ${VM_NAME}
    interfaces:
      - name: eno1
        macAddress: ${HOST_MAC}
    networkConfig:
      interfaces:
        - name: eno1
          type: ethernet
          state: up
          mac-address: ${HOST_MAC}
          ipv4:
            enabled: true
            address:
              - ip: ${HOST_IP}
                prefix-length: 24
      routes:
        config:
        - next-hop-address: ${HOST_ROUTE}
          next-hop-interface: eno1
          destination: 0.0.0.0/0
      dns-resolver:
        config:
          server:
            - ${HOST_ROUTE}