apiVersion: lca.openshift.io/v1alpha1
kind: ImageBasedUpgrade
metadata:
    name: upgrade
spec:
    stage: Idle
    seedImageRef:
        version: ${SEED_VERSION}
        image: ${SEED_IMAGE}
        pullSecretRef:
          name: seed-pull-secret
