apiVersion: v1beta1
kind: ImageBasedConfig
metadata:
  name: ${VM_NAME}-imagebased-config
  namespace: cluster0
hostname: ${VM_NAME}
releaseRegistry: ${RELEASE_REGISTRY}
networkConfig:
  interfaces:
    - name: enp1s0
      type: ethernet
      state: up
      mac-address: ${HOST_MAC}
      ipv4:
        enabled: true
        address:
          - ip: ${HOST_IP}
            prefix-length: 24
  routes:
    config:
    - next-hop-address: ${HOST_ROUTE}
      next-hop-interface: enp1s0
      destination: 0.0.0.0/0
  dns-resolver:
    config:
      server:
        - ${HOST_ROUTE}
