---
apiVersion: v1
data:
  config.yaml: "grafana:\n  enabled: false\nalertmanagerMain:\n  enabled: false\n\
    prometheusK8s:\n   retention: 24h\n"
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring

---
apiVersion: operator.openshift.io/v1
kind: Console
metadata:
 annotations:
   include.release.openshift.io/ibm-cloud-managed: 'false'
   include.release.openshift.io/self-managed-high-availability: 'false'
   include.release.openshift.io/single-node-developer: 'false'
   release.openshift.io/create-only: 'true'
 name: cluster
spec:
 logLevel: Normal
 managementState: Removed
 operatorLogLevel: Normal

# The rest of the configurations are commented out because it's something that
# differs per site, so it's better to keep it outside of the image

# ---
# apiVersion: logging.openshift.io/v1
# kind: ClusterLogForwarder
# metadata:
#   name: instance
#   namespace: openshift-logging
# spec:
#   inputs:
#     - infrastructure: {}
#       name: infra-logs
#   outputs:
#     - name: kafka-open
#       type: kafka
#       url: tcp://192.168.122.1:9092/test
#   pipelines:
#     - inputRefs:
#         - audit
#       name: audit-logs
#       outputRefs:
#         - kafka-open
#     - inputRefs:
#         - infrastructure
#       name: infrastructure-logs
#       outputRefs:
#         - kafka-open
# ---
# apiVersion: logging.openshift.io/v1
# kind: ClusterLogging
# metadata:
#   name: instance
#   namespace: openshift-logging
# spec:
#   collection:
#     logs:
#       fluentd: {}
#       type: fluentd
#   curation:
#     curator:
#       schedule: 30 3 * * *
#     type: curator
#   managementState: Managed

#---
#apiVersion: ptp.openshift.io/v1
#kind: PtpConfig
#metadata:
# name: du-ptp-slave
# namespace: openshift-ptp
#spec:
# profile:
#   - interface: ens5f0
#     name: slave
#     phc2sysOpts: -a -r -n 24
#     ptp4lConf: |
#       [global]
#       #
#       # Default Data Set
#       #
#       twoStepFlag 1
#       slaveOnly 0
#       priority1 128
#       priority2 128
#       domainNumber 24
#       #utc_offset 37
#       clockClass 255
#       clockAccuracy 0xFE
#       offsetScaledLogVariance 0xFFFF
#       free_running 0
#       freq_est_interval 1
#       dscp_event 0
#       dscp_general 0
#       dataset_comparison G.8275.x
#       G.8275.defaultDS.localPriority 128
#       #
#       # Port Data Set
#       #
#       logAnnounceInterval -3
#       logSyncInterval -4
#       logMinDelayReqInterval -4
#       logMinPdelayReqInterval -4
#       announceReceiptTimeout 3
#       syncReceiptTimeout 0
#       delayAsymmetry 0
#       fault_reset_interval 4
#       neighborPropDelayThresh 20000000
#       masterOnly 0
#       G.8275.portDS.localPriority 128
#       #
#       # Run time options
#       #
#       assume_two_step 0
#       logging_level 6
#       path_trace_enabled 0
#       follow_up_info 0
#       hybrid_e2e 0
#       inhibit_multicast_service 0
#       net_sync_monitor 0
#       tc_spanning_tree 0
#       tx_timestamp_timeout 50
#       unicast_listen 0
#       unicast_master_table 0
#       unicast_req_duration 3600
#       use_syslog 1
#       verbose 0
#       summary_interval 0
#       kernel_leap 1
#       check_fup_sync 0
#       #
#       # Servo Options
#       #
#       pi_proportional_const 0.0
#       pi_integral_const 0.0
#       pi_proportional_scale 0.0
#       pi_proportional_exponent -0.3
#       pi_proportional_norm_max 0.7
#       pi_integral_scale 0.0
#       pi_integral_exponent 0.4
#       pi_integral_norm_max 0.3
#       step_threshold 2.0
#       first_step_threshold 0.00002
#       max_frequency 900000000
#       clock_servo pi
#       sanity_freq_limit 200000000
#       ntpshm_segment 0
#       #
#       # Transport options
#       #
#       transportSpecific 0x0
#       ptp_dst_mac 01:1B:19:00:00:00
#       p2p_dst_mac 01:80:C2:00:00:0E
#       udp_ttl 1
#       udp6_scope 0x0E
#       uds_address /var/run/ptp4l
#       #
#       # Default interface options
#       #
#       clock_type OC
#       network_transport L2
#       delay_mechanism E2E
#       time_stamping hardware
#       tsproc_mode filter
#       delay_filter moving_median
#       delay_filter_length 10
#       egressLatency 0
#       ingressLatency 0
#       boundary_clock_jbod 0
#       #
#       # Clock description
#       #
#       productDescription ;;
#       revisionData ;;
#       manufacturerIdentity 00:00:00
#       userDescription ;
#       timeSource 0xA0
#     ptp4lOpts: -2 -s --summary_interval 0
#     ptpSchedulingPolicy: SCHED_FIFO
#     ptpSchedulingPriority: 10
# recommend:
#   - match:
#       - nodeLabel: node-role.kubernetes.io/master
#     priority: 4
#     profile: slave

# ---
# apiVersion: sriovnetwork.openshift.io/v1
# kind: SriovOperatorConfig
# metadata:
#   name: default
#   namespace: openshift-sriov-network-operator
# spec:
#   configDaemonNodeSelector:
#     node-role.kubernetes.io/master: ''
#   disableDrain: true
#   enableInjector: true
#   enableOperatorWebhook: true

# ---
# apiVersion: operator.openshift.io/v1
# kind: Network
# metadata:
#   name: cluster
# spec:
#   disableNetworkDiagnostics: true

# ---
# apiVersion: local.storage.openshift.io/v1
# kind: LocalVolume
# metadata:
#   name: local-disks
#   namespace: openshift-local-storage
# spec:
#   logLevel: Normal
#   managementState: Managed
#   storageClassDevices:
#     - devicePaths:
#         - /dev/vdb
#       fsType: xfs
#       storageClassName: example-storage-class-1
#       volumeMode: Filesystem
#     - devicePaths:
#         - /dev/vdc
#       fsType: xfs
#       storageClassName: example-storage-class-2
#       volumeMode: Filesystem
