---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  annotations:
    kubeletconfig.experimental: '{"containerLogMaxFiles": 50, "containerLogMaxSize":
      "100Mi"}
      '
    ran.openshift.io/reference-configuration: ran-du.redhat.com
  name: openshift-node-performance-profile
spec:
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ''
  nodeSelector:
    node-role.kubernetes.io/master: ''
  additionalKernelArgs:
    - rcupdate.rcu_normal_after_boot=0
    - efi=runtime
    - module_blacklist=irdma
  cpu:
    isolated: 0-7
    reserved: 8-15
  realTimeKernel:
    enabled: true
  workloadHints:
    highPowerConsumption: false
    perPodPowerManagement: false
    realTime: true
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - count: 16
        size: 1G
  numa:
    topologyPolicy: restricted

---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: performance-patch
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - name: performance-patch
      data: |
        [main]
        summary=Configuration changes profile inherited from performance created tuned
        ;include=openshift-node-performance-openshift-node-performance-profile

        [sysctl]
        kernel.timer_migration=1
        kernel.sysrq=1
        kernel.panic_on_rcu_stall=1
        kernel.hung_task_panic=1

        [scheduler]
        group.ice-ptp=0:f:10:*:ice-ptp.*

        [service]
        service.stalld=start,enable
  recommend:
    - machineConfigLabels:
        machineconfiguration.openshift.io/role: master
      priority: 19
      profile: performance-patch
